name: Warden Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # v3'ten v4'e yükseltildi

      - name: Setup Java 17
        uses: actions/setup-java@v4 # v3'ten v4'e yükseltildi
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3 # Güncellendi

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # KRİTİK: v3 yerine v4 yapıldı
        with:
          name: Warden-Client-Jar
          path: build/libs/*.jar
